name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.6

    - name: Build
      env: 
        CGO_ENABLED: 0
      run: |
        go mod download
        go build -ldflags '-s -w -extldflags "-static"' -v ./...
