name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1
        
    - name: Add Commit ID
      if: github.event_name != 'release'
      run: |
        ID=$(git rev-parse --short ${{ github.sha }})
        if [ "${{ github.event_name }}" == 'pull_request' ]
        then
          ID=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})
        fi
        sed -i '/build/ s/Custom/'$ID'/' ./main.go
        
    - name: Build
      env: 
        CGO_ENABLED: 0
      run: |
        go mod download
        go build -trimpath -ldflags '-s -w -extldflags "-static"' -v -o build_assets/simplereading 
        
    - name: run UPX
      uses: crazy-max/ghaction-upx@v1
      with:
        version: latest
        files: |
          ./build_assets/simplereading
        args:
          -9

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: simplereading
        path: |
          ./build_assets/*

        
    
